using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Hydris.Generators;

[Generator]
public sealed class ServiceGenerator : IIncrementalGenerator {
    private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

    private const string RendererSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace Hydris.Generated;

        internal static class GeneratedRenderer
        {
            [global::System.Runtime.CompilerServices.ModuleInitializer]
            internal static void Initialize()
            {
                global::Hydris.Bootstrap.RegisterServices(static c => c.Singleton<global::Hydris.Renderer.IRenderer>(static _ => new global::Hydris.QuickJs.QuickJsRenderer()));
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource("GeneratedBootstrap.g.cs",
            """
            // <auto-generated/>
            #nullable enable
            namespace Hydris.Generated;

            internal static class GeneratedBootstrap
            {
                [global::System.Runtime.CompilerServices.ModuleInitializer]
                internal static void Initialize()
                {
                    global::Hydris.Bootstrap.RegisterServices(static c => global::Hydris.Container.GeneratedServices.AddServices(c));
                    global::Hydris.Bootstrap.RegisterRoutes(static r => global::Hydris.Routing.GeneratedRoutes.MapRoutes(r));
                }
            }
            """));

        var hasQuickJs = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.GetTypeByMetadataName("Hydris.QuickJs.QuickJsRenderer") is not null);

        context.RegisterSourceOutput(hasQuickJs, static (production, present) => {
            if (present)
                production.AddSource("GeneratedRenderer.g.cs", RendererSource);
        });

        var singletons = Registrations(context, "Hydris.Container.SingletonAttribute", "Singleton");
        var scoped = Registrations(context, "Hydris.Container.ScopedAttribute", "Scoped");
        var transient = Registrations(context, "Hydris.Container.TransientAttribute", "Transient");
        var handlers = Registrations(context, "Hydris.Container.HandlerAttribute", "Scoped");
        var middlewares = Registrations(context, "Hydris.Middleware.MiddlewareAttribute", "Scoped");

        var combined = singletons.Collect()
            .Combine(scoped.Collect())
            .Combine(transient.Collect())
            .Combine(handlers.Collect())
            .Combine(middlewares.Collect());

        context.RegisterSourceOutput(combined, static (production, data) => {
            var ((((singleton, scope), transientLines), handlerLines), middlewareLines) = data;
            var lines = new List<string>();
            Collect(lines, singleton);
            Collect(lines, scope);
            Collect(lines, transientLines);
            Collect(lines, handlerLines);
            Collect(lines, middlewareLines);
            production.AddSource("GeneratedServices.g.cs", Emit(lines));
        });

        var routeGet = RouteRegistrations(context, "Hydris.Routing.GetAttribute", "Get");
        var routePost = RouteRegistrations(context, "Hydris.Routing.PostAttribute", "Post");
        var routePut = RouteRegistrations(context, "Hydris.Routing.PutAttribute", "Put");
        var routePatch = RouteRegistrations(context, "Hydris.Routing.PatchAttribute", "Patch");
        var routeDelete = RouteRegistrations(context, "Hydris.Routing.DeleteAttribute", "Delete");

        var routes = routeGet.Collect()
            .Combine(routePost.Collect())
            .Combine(routePut.Collect())
            .Combine(routePatch.Collect())
            .Combine(routeDelete.Collect());

        context.RegisterSourceOutput(routes, static (production, data) => {
            var ((((get, post), put), patch), delete) = data;
            var lines = new List<string>();
            Collect(lines, get);
            Collect(lines, post);
            Collect(lines, put);
            Collect(lines, patch);
            Collect(lines, delete);
            production.AddSource("GeneratedRoutes.g.cs", EmitRoutes(lines));
        });
    }

    private static IncrementalValuesProvider<string?> RouteRegistrations(
        IncrementalGeneratorInitializationContext context,
        string attribute,
        string httpMethod) {
        return context.SyntaxProvider.ForAttributeWithMetadataName(
            attribute,
            static (node, _) => node is MethodDeclarationSyntax,
            (syntax, _) => RouteRegistration(syntax, httpMethod));
    }

    private static string? RouteRegistration(GeneratorAttributeSyntaxContext syntax, string httpMethod) {
        if (syntax.TargetSymbol is not IMethodSymbol method)
            return null;
        if (syntax.Attributes.Length == 0)
            return null;

        var arguments = syntax.Attributes[0].ConstructorArguments;
        if (arguments.Length == 0 || arguments[0].Value is not string path)
            return null;

        var controller = method.ContainingType.ToDisplayString(FullyQualified);
        var literal = "\"" + path.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

        var uses = new List<string>();
        CollectUse(method.ContainingType.GetAttributes(), uses);
        CollectUse(method.GetAttributes(), uses);
        var chain = "[" + string.Join(", ", uses) + "]";

        var json = HasJson(method.ContainingType.GetAttributes()) || HasJson(method.GetAttributes())
            ? "true"
            : "false";

        return $"router.Map<{controller}>(global::Hydris.Routing.Method.{httpMethod}, {literal}, {chain}, {json}, static c => c.{method.Name}());";
    }

    private static void CollectUse(ImmutableArray<AttributeData> attributes, List<string> into) {
        foreach (var attribute in attributes) {
            var attributeClass = attribute.AttributeClass;
            if (attributeClass is null || attributeClass.TypeArguments.Length != 1)
                continue;
            var definition = attributeClass.OriginalDefinition;
            if (definition.Name != "MiddlewareAttribute"
                || definition.ContainingNamespace?.ToDisplayString() != "Hydris.Middleware")
                continue;
            into.Add($"typeof({attributeClass.TypeArguments[0].ToDisplayString(FullyQualified)})");
        }
    }

    private static bool HasJson(ImmutableArray<AttributeData> attributes) {
        foreach (var attribute in attributes) {
            if (attribute.AttributeClass?.ToDisplayString() == "Hydris.Http.JsonAttribute")
                return true;
        }

        return false;
    }

    private static string EmitRoutes(List<string> lines) {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Hydris.Routing;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedRoutes");
        builder.AppendLine("{");
        builder.AppendLine("    public static Router MapRoutes(this Router router)");
        builder.AppendLine("    {");
        foreach (var line in lines)
            builder.Append("        ").AppendLine(line);
        builder.AppendLine("        return router;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static IncrementalValuesProvider<string?> Registrations(
        IncrementalGeneratorInitializationContext context,
        string attribute,
        string lifetime) {
        return context.SyntaxProvider.ForAttributeWithMetadataName(
            attribute,
            static (node, _) => node is TypeDeclarationSyntax,
            (syntax, _) => Registration(syntax, lifetime));
    }

    private static string? Registration(GeneratorAttributeSyntaxContext syntax, string lifetime) {
        if (syntax.TargetSymbol is not INamedTypeSymbol type)
            return null;

        var constructor = type.InstanceConstructors
            .Where(candidate => candidate.DeclaredAccessibility == Accessibility.Public)
            .OrderByDescending(candidate => candidate.Parameters.Length)
            .FirstOrDefault();
        if (constructor is null)
            return null;

        var typeName = type.ToDisplayString(FullyQualified);
        var arguments = string.Join(
            ", ",
            constructor.Parameters.Select(parameter => $"r.Get<{parameter.Type.ToDisplayString(FullyQualified)}>()"));

        return $"container.{lifetime}(static r => new {typeName}({arguments}));";
    }

    private static void Collect(List<string> lines, ImmutableArray<string?> registrations) {
        foreach (var registration in registrations) {
            if (registration is not null)
                lines.Add(registration);
        }
    }

    private static string Emit(List<string> lines) {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Hydris.Container;");
        builder.AppendLine();
        builder.AppendLine("public static class GeneratedServices");
        builder.AppendLine("{");
        builder.AppendLine("    public static DiContainer AddServices(this DiContainer container)");
        builder.AppendLine("    {");
        foreach (var line in lines)
            builder.Append("        ").AppendLine(line);
        builder.AppendLine("        return container;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
