using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Hydris.Generators;

[Generator]
public sealed class ViewDataGenerator : IIncrementalGenerator {
    private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

    private static readonly DiagnosticDescriptor Unsupported = new(
        "HYD001",
        "Unsupported [ViewData] property type",
        "Property '{0}' of type '{1}' is not supported by [ViewData]; use string, bool, a numeric type, enum, DateTime, DateTimeOffset, Guid, a nested [ViewData] type, or a list/array of those",
        "Hydris",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Hydris.Http.ViewDataAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (syntax, _) => (INamedTypeSymbol)syntax.TargetSymbol);

        context.RegisterSourceOutput(types, static (production, type) => Emit(production, type));
    }

    private static void Emit(SourceProductionContext production, INamedTypeSymbol type) {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var keyword = type.IsRecord
            ? type.TypeKind == TypeKind.Struct ? "record struct" : "record"
            : type.TypeKind == TypeKind.Struct ? "struct" : "class";

        var body = new StringBuilder();
        foreach (var member in type.GetMembers()) {
            if (member is not IPropertySymbol prop)
                continue;
            if (prop.IsStatic || prop.IsIndexer || prop.DeclaredAccessibility != Accessibility.Public || prop.GetMethod is null)
                continue;

            var name = char.ToLowerInvariant(prop.Name[0]) + prop.Name.Substring(1);
            EmitWrite(production, body, "            ", $"\"{name}\"", prop.Type, $"this.{prop.Name}", prop, 0);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (ns is not null) {
            sb.Append("namespace ").AppendLine(ns);
            sb.AppendLine("{");
        }
        sb.Append("    partial ").Append(keyword).Append(' ').Append(type.Name).AppendLine(" : global::Hydris.Http.IViewData");
        sb.AppendLine("    {");
        sb.AppendLine("        void global::Hydris.Http.IViewData.Write(global::System.Text.Json.Utf8JsonWriter writer)");
        sb.AppendLine("        {");
        sb.AppendLine("            writer.WriteStartObject();");
        sb.Append(body);
        sb.AppendLine("            writer.WriteEndObject();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        if (ns is not null)
            sb.AppendLine("}");

        var hint = type.ToDisplayString(FullyQualified).Replace("global::", string.Empty).Replace('.', '_').Replace('<', '_').Replace('>', '_');
        production.AddSource($"{hint}.ViewData.g.cs", sb.ToString());
    }

    private static void EmitWrite(
        SourceProductionContext production,
        StringBuilder sb,
        string indent,
        string? name,
        ITypeSymbol type,
        string expr,
        IPropertySymbol prop,
        int depth) {
        var underlying = UnwrapNullable(type);
        if (underlying is not null) {
            sb.Append(indent).Append("if (").Append(expr).AppendLine(".HasValue)");
            sb.Append(indent).AppendLine("{");
            EmitWrite(production, sb, indent + "    ", name, underlying, $"{expr}.Value", prop, depth);
            sb.Append(indent).AppendLine("}");
            sb.Append(indent).AppendLine("else");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    ").AppendLine(name is null ? "writer.WriteNullValue();" : $"writer.WriteNull({name});");
            sb.Append(indent).AppendLine("}");
            return;
        }

        if (type.SpecialType == SpecialType.System_String) {
            Scalar(sb, indent, name, "String", expr);
            return;
        }
        if (type.SpecialType == SpecialType.System_Boolean) {
            Scalar(sb, indent, name, "Boolean", expr);
            return;
        }
        if (IsNumeric(type.SpecialType)) {
            Scalar(sb, indent, name, "Number", expr);
            return;
        }
        if (type.TypeKind == TypeKind.Enum) {
            Scalar(sb, indent, name, "String", $"{expr}.ToString()");
            return;
        }
        var full = type.ToDisplayString(FullyQualified);
        if (full is "global::System.Guid" or "global::System.DateTime" or "global::System.DateTimeOffset") {
            Scalar(sb, indent, name, "String", expr);
            return;
        }
        if (ImplementsViewData(type)) {
            Nested(sb, indent, name, expr);
            return;
        }
        var element = ElementType(type);
        if (element is not null) {
            Sequence(production, sb, indent, name, element, expr, prop, depth);
            return;
        }

        production.ReportDiagnostic(Diagnostic.Create(
            Unsupported, prop.Locations.FirstOrDefault(), prop.Name, type.ToDisplayString()));
    }

    private static void Scalar(StringBuilder sb, string indent, string? name, string kind, string expr) {
        sb.Append(indent).Append("writer.Write").Append(kind);
        sb.Append(name is null ? "Value(" : $"({name}, ");
        sb.Append(expr).AppendLine(");");
    }

    private static void Nested(StringBuilder sb, string indent, string? name, string expr) {
        if (name is not null)
            sb.Append(indent).Append("writer.WritePropertyName(").Append(name).AppendLine(");");
        sb.Append(indent).Append("if (").Append(expr).AppendLine(" is null) { writer.WriteNullValue(); }");
        sb.Append(indent).Append("else { ((global::Hydris.Http.IViewData)").Append(expr).AppendLine(").Write(writer); }");
    }

    private static void Sequence(
        SourceProductionContext production,
        StringBuilder sb,
        string indent,
        string? name,
        ITypeSymbol element,
        string expr,
        IPropertySymbol prop,
        int depth) {
        var item = $"__e{depth}";
        if (name is not null)
            sb.Append(indent).Append("writer.WritePropertyName(").Append(name).AppendLine(");");
        sb.Append(indent).Append("if (").Append(expr).AppendLine(" is null) { writer.WriteNullValue(); }");
        sb.Append(indent).AppendLine("else");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    writer.WriteStartArray();");
        sb.Append(indent).Append("    foreach (var ").Append(item).Append(" in ").Append(expr).AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        EmitWrite(production, sb, indent + "        ", null, element, item, prop, depth + 1);
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("    writer.WriteEndArray();");
        sb.Append(indent).AppendLine("}");
    }

    private static ITypeSymbol? UnwrapNullable(ITypeSymbol type) =>
        type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            ? named.TypeArguments[0]
            : null;

    private static bool IsNumeric(SpecialType type) => type
        is SpecialType.System_Byte
        or SpecialType.System_SByte
        or SpecialType.System_Int16
        or SpecialType.System_UInt16
        or SpecialType.System_Int32
        or SpecialType.System_UInt32
        or SpecialType.System_Int64
        or SpecialType.System_UInt64
        or SpecialType.System_Single
        or SpecialType.System_Double
        or SpecialType.System_Decimal;

    private static bool ImplementsViewData(ITypeSymbol type) =>
        type.AllInterfaces.Any(static i => i.ToDisplayString(FullyQualified) == "global::Hydris.Http.IViewData")
        || type.GetAttributes().Any(static a => a.AttributeClass?.ToDisplayString() == "Hydris.Http.ViewDataAttribute");

    private static ITypeSymbol? ElementType(ITypeSymbol type) {
        if (type is IArrayTypeSymbol array)
            return array.ElementType;
        if (type.SpecialType == SpecialType.System_String)
            return null;
        foreach (var candidate in type.AllInterfaces) {
            if (candidate.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                return candidate.TypeArguments[0];
        }

        return null;
    }
}
